# -*- coding: utf-8 -*-
"""1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MBp2OXELpHjZk5O5WZvMzTpylM2dv2pa
"""

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("https://raw.githubusercontent.com/Zzero76/Machine-learning/main/123.csv")
df = df.drop(columns=['E','F','V','W','X','Y'])

X = df.drop(columns=['AH'])
y = df['AH']

print(df.head())
print(df.describe())
print(df.isnull().sum())
plt.figure(figsize=(15, 10))  # Set the figure size for better readability
correlation_matrix = df.corr()  # Calculate the correlation matrix
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix of Features and Target")
plt.show()

